POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Sam",
  "name": "Adam Richard",
  "password": "ricfdff",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard@123"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard@456",
  "newPassword": "ric"
}
